### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by clonmac** [BlueWallet/LndHub#11]
Unable to start server

I'm sure this is user error of some sort, but I am unable to get LndHub deployed. I am trying to deploy this in a node.js Docker container on a Raspberry Pi with my bitcoind and lnd node, but it keeps erroring out when trying to start. The container runs with the 'npm start' command and gets to the point in the startup script of displaying the listening port, then it bombs out with the following message:

```
2019-02-04T15:58:49.147Z 'BOOTING UP' 'Listening on port 3000'
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:12914
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:12914
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
bitcoind failure
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! LndHub@1.1.1 start: `babel-node index.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the LndHub@1.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bitcoinuser/.npm/_logs/2019-02-04T15_58_50_368Z-debug.log
```

Within the mentioned log is the following:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.5.0
3 info using node@v11.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle LndHub@1.1.1~prestart: LndHub@1.1.1
6 info lifecycle LndHub@1.1.1~start: LndHub@1.1.1
7 verbose lifecycle LndHub@1.1.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle LndHub@1.1.1~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/lndhub/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle LndHub@1.1.1~start: CWD: /lndhub
10 silly lifecycle LndHub@1.1.1~start: Args: [ '-c', 'babel-node index.js' ]
11 silly lifecycle LndHub@1.1.1~start: Returned: code: 2  signal: null
12 info lifecycle LndHub@1.1.1~start: Failed to exec start script
13 verbose stack Error: LndHub@1.1.1 start: `babel-node index.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid LndHub@1.1.1
15 verbose cwd /lndhub
16 verbose Linux 4.9.35-v7+
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v11.9.0
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 2
22 error LndHub@1.1.1 start: `babel-node index.js`
22 error Exit status 2
23 error Failed at the LndHub@1.1.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

It appears from the first error output that it isn't communicating with redis, but I'm not sure if I missed something with the configuration there or not. Any help would be much appreciated. I'm not too familiar with running a node.js server, but hopefully I can help with any info you need. Thanks.

**Comment by Overtorment** [comment]
Hello! Happy to help.
Clearly Redis issue.  If inside docker, does it have redis inside as well..?
To make things simpler I'd recommend https://redislabs.com for development purposes (for production use you'll need to enable disk persistence and failover replication)

**Comment by clonmac** [comment]
Yes, I did download, compile and install the latest stable of redis inside my container. That was it though, I didn't have anything else in my Dockerfile to create any DB or do any configuration. I wasn't sure if anything needed to be done there or not prior to running 'npm i'.

**Comment by Overtorment** [comment]
Obviously you need to tune config.js but like youve already done that.
Well, you need to mess around your redis. It is probably not running or smth

**Comment by clonmac** [comment]
OK, I appreciate the direction. I'll do some more homework on my end to figure out what configuration I need to do. Thanks again.
