### ISSUE TITLE
Bitcoind version supported; listtransations RPC call and Accounts feature deprecation

### ISSUE THREAD

**Issue by alerobrod** [BlueWallet/LndHub#12]
While installing and testing LndHub this month, I noticed I had to change the code to conform to the specification for the RPC calls made to bitcoins (v0.17.0).

Specifically in ./class/User.js file to set the account attribute on some RPC calls (e.g. listtransactions) to a dummy value ('*').

Could you confirm which bitcoind version is LndHub meant to support? If the latest (0.17.0) what could be the cause for the error:

`jayson/lib/client/http.data:  {"result":null,"error":{"code":-8,"message":"Dummy value must be set to \"*\""},"id":"1b427b5b-cf89-4a7c-846a-a63435327b10"}

(node:29157) UnhandledPromiseRejectionWarning: Error: {"result":null,"error":{"code":-8,"message":"Dummy value must be set to \"*\""},"id":"1b427b5b-cf89-4a7c-846a-a63435327b10"}

    at IncomingMessage.<anonymous> (/home/pi/Projects/LndHub/node_modules/jayson/lib/client/http.js:76:21)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

Thank you and if you need anything else to provide feedback, let me know.

Much appreciated!

**Comment by Overtorment** [comment]
Hello! Running 0.17.0 in production, but with `-deprecatedrpc=accounts` option. Forgot to mention that.

If you can fix Lndhub to work without that option and send a PR that would be awesome.

**Comment by alerobrod** [comment]
Thanks for the answer. Will try and report if I see any issues (wonder if it could break other client software I am using).

The hot fix I applied likely causes issues if, say, we use more than one app (multi-user) towards the same LndHub instance (unless BlueWallet filters out based on address associated to user of a given app?).

Since I am new to this world, I think will try and fix this as you suggested (good way to learn by doing).

Thanks.
