### ISSUE TITLE
bitcoind failure

### ISSUE THREAD

**Issue by talentpierre** [BlueWallet/LndHub#36]
We trying to get lndhub running but get this error message for 
` node build/index.js`
```
(node:5567) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
2019-07-27T12:47:51.686Z : info: [BOOTING UP] : "Listening on port 3000"
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
bitcoind failure
```
can anybody please help?

**Comment by ianthius** [comment]
If you try hitting redis on your machine via the command line what do you get?

Try the following:
$ redis-cli
127.0.0.1:6379> ping

Do you get ?

PONG
127.0.0.1:6379> exit

**Comment by DaniW42** [comment]
We did, redis answered as suggested by you.

**Comment by Overtorment** [comment]
Correct launch command is `npm start` or `node_modules/.bin/babel-node index.js`, but ok, maybe youve built it.

`bitcoind failure` suggests that you did not configure bitcoind correctly. well, and probably redis too.
try running `telnet 127.0.0.1 6379`

**Comment by DaniW42** [comment]
So, we tried `npm start`, this is what happened:
```
> LndHub@1.1.1 start /home/bitcoin/LndHub
> babel-node index.js

using config {"bitcoind":{"rpc":"http://<userhere>:<passwordhere>@127.0.0.1:8333"},"redis":{"port":6379,"host":"127.0.0.1","family":4,"password":"","db":0},"lnd":{"url":"127.0.0.1:10009","password":""}}
using tls.cert <tlscerthere>
using macaroon <macaroonhere>
updateLightning()
updated
(node:2886) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
2019-08-06T18:55:57.582Z : info: [BOOTING UP] : "Listening on port 3000"
bitcoind failure
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! LndHub@1.1.1 start: `babel-node index.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the LndHub@1.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bitcoin/.npm/_logs/2019-08-06T18_55_57_712Z-debug.log
```
When using `node_modules/.bin/babel-node index.js`:
```
-same as above, but:-
updateLightning()
updated
(node:2779) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
2019-08-06T18:55:20.503Z : info: [BOOTING UP] : "Listening on port 3000"
bitcoind failure

```
`cat /home/bitcoin/.npm/_logs/2019-08-06T18_55_57_712Z-debug.log`
>> https://pastebin.com/9CjH3C10

`telnet 127.0.0.1 6379` is working as expected ( when i send ping, i get a pong )

We installed redis using apt-get because compiling did not work for us.

**Comment by Overtorment** [comment]
bitcoind is misconfifured

**Comment by talentpierre** [comment]
do you know what exactly is misconfigured? how can wie fix that? what are your recommendations?

**Comment by DaniW42** [comment]
Just found out that our bitcoind-log shows a lot of these:

```
2019-08-07T13:16:07Z socket recv error Connection reset by peer (104)
2019-08-07T13:21:01Z socket recv error Connection reset by peer (104)
2019-08-07T13:22:51Z socket recv error Connection reset by peer (104)
2019-08-07T13:24:14Z socket recv error Connection reset by peer (104)
2019-08-07T13:34:19Z socket recv error Connection reset by peer (104)
2019-08-07T13:39:31Z UpdateTip: new best=0000000000000000000232f121d153c858a8037118f808423b371f0e3ee5ca9b height=589055 version=0x20000000 log2_work=90.936558 tx=442723962 date='2019-08-07T13:39:06Z' progress=1.000000 cache=19.8MiB(152923txo) warning='44 of last 100 blocks have unexpected version'
2019-08-07T13:39:52Z UpdateTip: new best=0000000000000000000ae4f6e8ee389771556b1ae7b6ceec053441f88fb07a2f height=589056 version=0x20000000 log2_work=90.936584 tx=442726265 date='2019-08-07T13:39:31Z' progress=1.000000 cache=20.4MiB(158206txo) warning='43 of last 100 blocks have unexpected version'
2019-08-07T13:48:04Z socket recv error Connection reset by peer (104)
2019-08-07T13:48:04Z socket send error Broken pipe (32)
2019-08-07T13:59:44Z UpdateTip: new best=0000000000000000001b04e988f7dd61c061fc6dd75fb370b820a7305383cf02 height=589057 version=0x20000000 log2_work=90.93661 tx=442729252 date='2019-08-07T13:59:23Z' progress=1.000000 cache=21.8MiB(172089txo) warning='43 of last 100 blocks have unexpected version'
2019-08-07T14:04:40Z UpdateTip: new best=000000000000000000150ae653f3d414d1c7ae3992957999a9478102956294cf height=589058 version=0x20000000 log2_work=90.936636 tx=442731840 date='2019-08-07T14:04:40Z' progress=1.000000 cache=22.6MiB(179438txo) warning='42 of last 100 blocks have unexpected version'
2019-08-07T14:07:58Z Pre-allocating up to position 0x900000 in rev01749.dat
2019-08-07T14:07:58Z UpdateTip: new best=00000000000000000004b83ea27e85565257fb753566eee48ad6b3fee6608060 height=589059 version=0x20000000 log2_work=90.936663 tx=442733144 date='2019-08-07T14:07:53Z' progress=1.000000 cache=23.2MiB(185086txo) warning='41 of last 100 blocks have unexpected version'
2019-08-07T14:09:41Z socket recv error Connection reset by peer (104)
2019-08-07T14:10:44Z socket recv error Connection reset by peer (104)
2019-08-07T14:14:32Z socket recv error Connection reset by peer (104)
2019-08-07T14:18:38Z UpdateTip: new best=00000000000000000012066fd06bc5298daeaebecdff2361fecaa124227e31a2 height=589060 version=0x20400000 log2_work=90.936689 tx=442734923 date='2019-08-07T14:18:16Z' progress=1.000000 cache=24.2MiB(193742txo) warning='42 of last 100 blocks have unexpected version'
2019-08-07T14:19:40Z socket recv error Connection timed out (110)
2019-08-07T14:23:49Z socket recv error Connection reset by peer (104)
2019-08-07T14:24:20Z socket recv error Connection reset by peer (104)
2019-08-07T14:31:26Z socket recv error Connection reset by peer (104)

```

We will try to investigate this, do you have any idea?
This is our bitcoin.conf:

```
# RaspiBolt: bitcoind configuration
# /home/bitcoin/.bitcoin/bitcoin.conf

# remove the following line to enable Bitcoin mainnet
#mainnet=1

# Bitcoind options
server=1
daemon=1

# Connection settings
rpcuser=<userhere>
rpcpassword=<passwordhere>

onlynet=ipv4
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333

# Raspberry Pi optimizations
dbcache=100
maxorphantx=10
maxmempool=50
maxconnections=40
maxuploadtarget=5000

deprecatedrpc=accounts
```

**Comment by Overtorment** [comment]
Looks forgotten:

-rpcbind=0.0.0.0  -txindex  -rpcallowip=0.0.0.0/0 -server=1

(thats part of my configuration)

Also, show me your config from lndhub, the part about bitcoind

**Comment by DaniW42** [comment]
Thank you for staying tuned!

As for now I added `rpcbind=0.0.0.0` and `rpcallowip=0.0.0.0/0` which somehow fixed the `socket recv error Connection reset by peer` error messages. I now get a lot of this `New outbound peer connected: version: 70015, blocks=589357, peer=62`.

Unfortunately we still get those errors from https://github.com/BlueWallet/LndHub/issues/36#issuecomment-518802512

This is our config.js file from inside LndHub Folder:
```
let config = {
  bitcoind: {
    rpc: 'http://<userhere>:<passwordhere>@127.0.0.1:8333',
  },
  redis: {
    port: 6379,
    host: '127.0.0.1',
    family: 4,
    password: '',
    db: 0,
  },
  lnd: {
    url: '127.0.0.1:10009',
    password: '',
  },
};

if (process.env.CONFIG) {
  console.log('using config from env');
  config = JSON.parse(process.env.CONFIG);
}

module.exports = config;
```

What looks like double-quotation are two single-quotation marks.

**Comment by Overtorment** [comment]
Sorry for late reply.
Port `8333` doesnt look right, should be `8332`. One is a peer-to-peer port for communication with other nodes, the second one is for RPC.

**Comment by DaniW42** [comment]
Thanks! It somehow changed something, unfortunately we are now getting a totally different error message after running `node_modules/.bin/babel-node index.js`:

```
(node:6109) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
2019-08-31T21:27:09.948Z : info: [BOOTING UP] : "Listening on port 3000"
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
```
The `[ioredis]` part keeps showing up until canceled by Ctrl+C. Port 6379 sounds like a redis-related problem?

**Comment by Overtorment** [comment]
Yep, looks like can't connect to Redis

**Comment by DaniW42** [comment]
Could this be a user-rights problem? 

The user which starts `node_modules/.bin/babel-node index.js` has no root rights and is not capable of running sudo

**Comment by Overtorment** [comment]
No, this is not rights. My bet is something wrong with redis process

**Comment by lessless** [comment]
@Overtorment  I guess this can be closed.
